services:
  # ========================================
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus:rw
  #      - /mnt/pitwall/prometheus:/prometheus:rw
    ports:
      - 10100:9090
  # ========================================
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 10000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
  # ========================================
  vortex:
    image: pitwalldatagatheringapi:latest
    container_name: pitwalldatagatheringapi
    environment:
      - VortexSimerKey=some_test_looking_value23
      - DatabaseLeaderboardDatabase=Server=sqldatabase;User=root;Password=password;ConvertZeroDateTime=True;
      - ASPNETCORE_HTTP_PORTS=80
      # - ASPNETCORE_HTTPS_PORTS=443
    ports:
      - 32773:80
    # - 32772:443
