services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 10100:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - /mnt/pitwall/prometheus:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 10000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
  sqldatabase:
    image: mysql
    command: --default-authentication-plugin caching_sha2_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - /mnt/databases/mysql:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  vortex:
    image: pitwalldatagatheringapi:latest
    container_name: pitwalldatagatheringapi
    environment:
      - VortexSimerKey=some_test_looking_value23
      - ASPNETCORE_HTTP_PORTS=80
      # - ASPNETCORE_HTTPS_PORTS=443
    ports:
      - 32773:80
     # - 32772:443