# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: PowerShell@2
      name: diagnostic
      inputs:
        targetType: inline
        script: 'pwd'
    - task: PowerShell@2
      displayName: 'Move to src folder'
      inputs:
        targetType: inline
        script: 'cd $(Build.SourcesDirectory)/src'

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'PitWallDataGatheringApi/PitWallDataGatheringApi/Dockerfile'
        tags: |
          $(tag)
