# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'pitwall-api'

stages:
- stage: ContinuousIntegration
  displayName: Local Build and Tests
  jobs:
  - job: BuildAndRunTests
    displayName: Build solution and run tests
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore package
      inputs:
        command: 'restore'
        projects: '**/*.sln'
        workingDirectory: 'src/PitWallDataGatheringApi'

    - task: DotNetCoreCLI@2
      displayName: Build solution
      inputs:
        command: 'build'
        projects: '**/*.sln'
        workingDirectory: 'src/PitWallDataGatheringApi'

    - task: DotNetCoreCLI@2
      displayName: Run tests
      inputs:
        command: 'test'
        projects: '**/*.sln'
        arguments: '--filter FullyQualifiedName!~Integration.Tests --collect "Code Coverage" --settings ci-tests.runsettings'
        workingDirectory: 'src/PitWallDataGatheringApi'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'